### PR TITLE
Update ac.tdwg.org to new design

### PR DESCRIPTION
**Pull request by peterdesmet**
This PR implements #250. It does not include any changes to the standard itself.

## Updates to make use of new design

- Update `_config.yml`
- Move navigation to `_data/navigation.yml` and include some horizontal lines in dropdowns for better separation of content that belongs together
- Add footer information
- Add favicon
- Add Gemfile to allow local build

## Dropdown

@baskaufs I made a change to the dropdown menu for **terms**, so it is clearer to read. The titles of the pages themselves have not been changed (though some are quite long).

Before:

Screenshot 2023-03-06 at 16 51 33

After:

Screenshot 2023-03-06 at 16 25 49

## Versioned pages

@baskaufs you mentioned in https://github.com/tdwg/ac/issues/250#issuecomment-1448333302:

> Because of their directory structure, the DwC version URLs will pick up the same styling as the current version.

That is true, but the reason that doesn't work for the AC ones is not because of the directory structure, but because their frontmatter metadata all had the non-versioned `permalink` (i.e. multiple pages with same permalink) and were therefore not accessible. Except for two pages which have the correct permalink:

https://ac.tdwg.org/structure/2013-10-23
https://ac.tdwg.org/termlist/2013-10-23

I've now set versioned permalinks for all. @baskaufs, you're still welcome to organize pages in directories, so the permalink is automatically picked up from the directory organization.

## Sitemap

```
/
/format/2020-10-13
/format/
/guide/2013-10-15
/guide/
/introduction/2013-10-23
/introduction/
/structure/2013-10-23
/structure/2020-01-27
/structure/2021-10-05
/structure/
/subtype/2020-10-13
/subtype/2022-02-23
/subtype/
/termlist/2013-10-23
/termlist/2020-01-27
/termlist/2020-08-23
/termlist/2020-10-13
/termlist/2021-02-01
/termlist/2021-10-05
/termlist/2022-02-23
/termlist/
/variant/2020-10-13
/variant/
```

## Preview

Audiovisual-Core-Term-List-Audiovisual-Core

### CODE REVIEW

**Review by baskaufs — APPROVED** [review]
@peterdesmet I like all of these changes. The bar in the dropdown is good and I've always been unhappy that so few of the sections showed up in the navigation, so I think that change is also good. 

In retrospect, I suppose I should have done all of the page rearrangement on this branch rather than on the master. I hope those conflicts won't be too hard to resolve. I've updated the page redirection in the rs.tdwg.org repo, so it's all working now -- the versioned pages are styled now and the hyperlinks between all of the versions work.

**Comment by peterdesmet** [comment]
@baskaufs conflicts resolved.

Now that the files are in directories reflecting their path, it is no longer necessary to define/hardcode the `permalink` for each one, so I have removed those. That way we don't have conflicting information. We do the same for Darwin Core.

The URLs will remain the same for all `index.md` files. For the versioned pages, the URL will change from:

```
introduction/2013-10-23 -> introduction/2013-10-23.html
```

But the effect in the browser is the same and the pages can be found at either URL. Note that the original permalinks did not have an ending slash, which would have been a breaking change.

**Comment by baskaufs** [comment]
OK, great. Simpler is better. As long as the URLs without trailing slashes dereference, it's all good.

**Comment by peterdesmet** [comment]
Site is now live at https://ac.tdwg.org/

I do notice an rs.tdwg.org redirection error, but will create a separate issue for that.

**Comment by baskaufs** [comment]
@peterdesmet Beautiful! Thanks so much for getting this done!

**Pull request merged**
